apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: #these are deployment labels
    purpose: helm-demo
    project: roboshop
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: #these labels are used to select pods
      purpose: helm-demo
      project: roboshop
  template: #pod definition
    metadata:
      labels:
        purpose: helm-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}
        ports:
        - containerPort: 80