apiVersion: v1
kind: Service
metadata:
  name: service-lb
spec:
  type: {{ .Values.service.type }}
  selector:
    purpose: helm-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: 80
      nodePort: 30005